spring:
  data:
    mongodb:
      uri: mongodb://192.168.9.177:27017/xchs_saas_school_demo
  datasource:
    url: jdbc:mysql://192.168.9.177:3306/xchs_saas_school_demo?autoReconnect=true&autoReconnectForPools=true&useSSL=false&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull
    username: root
    password: xchs996832
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    database: 0
    host: 192.168.9.177
    port: 6379
    password:
    timeout: 5000
    lettuce:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    publisher-confirms: true
official:
  host: 192.168.9.177
  port: 7001
  security: http
  secret: wK6VIad708ssnao31u0uGDOBEuMd
local:
  school-id: demo
