spring:
  profiles:
    active: dev
  application:
    name: core
  jmx:
    default-domain: ${spring.application.name}
  jpa:
    database: MYSQL
    show-sql: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  output:
    ansi:
      enabled: detect
  session:
    store-type: none
  redis:
    timeout: 5000
  rabbitmq:
    listener:
      simple:
        default-requeue-rejected: false
      direct:
        default-requeue-rejected: false
    connection-timeout: 0
logging:
  config: classpath:logback-spring.xml
server:
  port: 8888
  servlet:
    session:
      cookie:
        max-age: 0
      timeout: 1
      persistent: false
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
ribbon:
  ReadTimeout: 1200000 # 处理时间
  ConnectTimeout: 6000 # 连接时间
jodconverter:
  enabled: true
hystrix:
    command:
      default:
        execution:
          isolation:
            thread:
              timeoutInMilliseconds: 3000
async:
  executor:
    thread:
      corePoolSize: 5
      maxPoolSize: 5
      queueCapacity: 9999
      waitForTasksToCompleteOnShutdown: true
      awaitTerminationSeconds: 60
      threadNamePrefix: core-async