spring:
  profiles:
    active: dev
  application:
    name: apartment
  jmx:
    default-domain: ${spring.application.name}
  jpa:
    database: MYSQL
    show-sql: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  session:
    store-type: none
  redis:
    timeout: 5000
mybatis:
  type-aliases-package: com.xchs.apartment.module  # 注意：对应实体类的路径
  configuration:
    map-underscore-to-camel-case: true
    default-enum-type-handler: org.apache.ibatis.type.EnumTypeHandler
mapper:
  mappers: com.xchs.apartment.base.ElementaryMapper
  identity: mysql
  useSimpleType: true
  enumAsSimpleType: true
  notEmpty: true
pagehelper:
  helperDialect: mysql
  supportMethodsArguments: true
  params: count=countSql
server:
  port: 8763
  servlet:
    session:
      cookie:
        max-age: 0
      timeout: 1
      persistent: false
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000
logging:
  config: classpath:logback-spring.xml